action.configuration.remote_entity:migration_update:*:
  type: action_configuration_default
  label: 'Update given remote entity'

helfi_api_base.environment_resolver.settings:
  type: config_entity
  mapping:
    environment_name:
      type: string
      label: 'The currently active environment name'
    project_name:
      type: string
      label: 'The currently active project name'

log_stdout.settings:
  type: config_object
  label: 'Log stdout settings'
  mapping:
    format:
      type: string
      label: 'Format'
    use_stderr:
      type: string
      label: 'Use stderr'
