on: [push]
name: CI
env:
  SIMPLETEST_DB: "mysql://drupal:drupal@db:3306/drupal"
  SIMPLETEST_BASE_URL: "http://127.0.0.1:8080"
  DRUPAL_MODULE_NAME: helfi_api_base
  DRUPAL_CORE_VERSION: 9.1.x
jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/city-of-helsinki/drupal-php-docker:7.4

    services:
      db:
        image: druidfi/db:mysql5.7-drupal
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set variables
        run: echo "DRUPAL_ROOT=$HOME/drupal" >> $GITHUB_ENV

      - name: Build project
        run: |
          composer global require tuutti/drupal-test-runner ^1.0
          drupal-tr
          cd $DRUPAL_ROOT
          echo "$(jq --indent 4 '.repositories |= [{"type": "path", "url": "https://repository.drupal.hel.ninja/"}] + .' composer.json)" > composer.json
          composer require drupal/$MODULE_NAME
          drush en $MODULE_NAME -y

      - name: Run PHPCS
        run: |
          cd $DRUPAL_ROOT
          vendor/bin/phpcs modules/custom/ --standard=Drupal

      - name: Run PHPUnit tests
        run: |
          TEST_RUNNER=core drupal-tr run-tests
