on:
  pull_request:
  push:
    branches:
      - main
name: CI
env:
  SYMFONY_DEPRECATIONS_HELPER: disabled
  BROWSERTEST_OUTPUT_DIRECTORY: 'public/sites/simpletest'
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.1', '8.2']
    container:
      image: ghcr.io/city-of-helsinki/drupal-php-docker:${{ matrix.php-versions }}-alpine

    services:
      db:
        image: mysql:8
        env:
          MYSQL_USER: drupal
          MYSQL_PASSWORD: drupal
          MYSQL_DATABASE: drupal
          MYSQL_ROOT_PASSWORD: drupal
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Parse $MODULE_NAME from composer.json
        run: echo "MODULE_NAME=$(cat composer.json | jq -r .name | awk -F/ '{print $NF}')" >> $GITHUB_ENV

      - name: Set Drupal root
        run: echo "DRUPAL_ROOT=$GITHUB_WORKSPACE/sut" >> $GITHUB_ENV

      - name: Install required composer dependencies
        run: composer install

      - name: Install Drupal
        working-directory: ${{ env.DRUPAL_ROOT }}
        run: |
          php -d sendmail_path=$(which true); vendor/bin/drush --yes -v site-install minimal --db-url="$SIMPLETEST_DB"
          vendor/bin/drush en $MODULE_NAME -y

      - name: Run PHPCS
        working-directory: ${{ env.DRUPAL_ROOT }}
        run: vendor/bin/phpcs --ignore=*/vendor/*,*/sut/* . --standard=Drupal,DrupalPractice --extensions=php,module,install .

      - name: Run phpstan
        working-directory: ${{ env.DRUPAL_ROOT }}
        run: vendor/bin/phpstan analyze -c phpstan.neon .

      - name: Start services
        working-directory: ${{ env.DRUPAL_ROOT }}
        run: vendor/bin/drush runserver $SIMPLETEST_BASE_URL --dns > /dev/null 2>&1 &

      - name: Run PHPUnit tests
        working-directory: ${{ env.DRUPAL_ROOT }}
        run: |
          vendor/bin/phpunit -c tests/phpunit.xml tests/
          codecov
